// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjFinalTeam4.Data;

#nullable disable

namespace ProjFinalTeam4.Migrations
{
    [DbContext(typeof(ProjFinalTeam4Context))]
    [Migration("20241121183018_TeamProjFinalDatabase")]
    partial class TeamProjFinalDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjFinalTeam4.Models.Hobbies", b =>
                {
                    b.Property<int>("hobbiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hobbiesId"));

                    b.Property<string>("hobbiesDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hobbiesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hobbiesResources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hobbiesStart")
                        .HasColumnType("int");

                    b.HasKey("hobbiesId");

                    b.ToTable("Hobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
